#
# riscv64.conf
#
# Copyright (C) 2019-2025 Udo Steinberg, BlueRock Security, Inc.
#
# This file is part of the NOVA microhypervisor.
#
# NOVA is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# NOVA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License version 2 for more details.
#

# Configure cross-toolchain prefix (see README.md)
PREFIX		?= riscv64-linux-gnu-

# Default BOARD
BOARD		?= qemu

# Configure architecture-specific run targets
RUN		?= qemu-system-riscv64 -m 512 -smp 4 -cpu rva23s64 -nographic -M virt -bios default

# Configure architecture-specific ELF image tweaks
H2E		?= ln -frs

# Configure architecture-specific BIN image tweaks
H2B		?= $(TGT_OC) -O binary

# Configure architecture-specific machine flags
MFLAGS		:= -march=rv64imafdc -mabi=lp64d -mcmodel=medany -mno-relax

# Configure architecture-specific preprocessor defines
ARCH_DEFINES	:= BOARD_$(BOARD)

# Configure architecture-specific warning flags
ARCH_WFLAGS	:= $(call check,-Wpedantic)

# Configure architecture-specific install integrity check
INSTALL_INTEGRITY := no

